stages:
  - website-full-deploy
  - website-doc-deploy
  - trigger

website-full-deploy:
  only: [ "2.0" ]
  stage: website-full-deploy
  tags:
    - docker
  image: "registry.gitlab.com/tarantool/doc"
  script:
    - cmake . && make
    - echo ${RSYNC_PASSWORD} > rsync.password
    - chmod 600 rsync.password
    - rsync -Pav --password-file=rsync.password output/
        ${RSYNC_USER}@${RSYNC_HOST}::tarantool-org/
    - rm -f rsync.password

website-doc-deploy:
  only: [ "1.6", "1.9", "2.0" ]
  stage: website-doc-deploy
  tags:
    - docker
  image: "registry.gitlab.com/tarantool/doc"
  script:
    - cmake . && make
    - echo ${RSYNC_PASSWORD} > rsync.password
    - chmod 600 rsync.password
    - rsync -Pav --password-file=rsync.password output/en/doc/${CI_COMMIT_REF_NAME}/
        ${RSYNC_USER}@${RSYNC_HOST}::tarantool-org/en/doc/${CI_COMMIT_REF_NAME}/
    - rsync -Pav --password-file=rsync.password output/ru/doc/${CI_COMMIT_REF_NAME}/
        ${RSYNC_USER}@${RSYNC_HOST}::tarantool-org/ru/doc/${CI_COMMIT_REF_NAME}/
    - rm -f rsync.password

trigger:
  only: [ "2.0" ]
  stage: trigger
  script:
    - "curl -X POST -F token=${TARANTOOLIO_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4657341/trigger/pipeline"
