language: generic # don't install any environment
install:
    - pip install sphinx==1.4.4 pelican BeautifulSoup sphinx-intl PyYAML --user
script: bash ./documentation.sh
env:
  global:
    - ENCRYPTION_LABEL: "cc37864fc395"

